name: Hourly DNS Check

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 */4 * * *"

  workflow_dispatch:

jobs:
  build-and-run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build DNS Checker for CI
        run: go build -v -o dns-checker ./dns-checker-ci

      - name: Run DNS Checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./dns-checker --domains ${{ vars.TARGET_DOMAINS }}
